### PR TITLE
Install libyuv to fix webm recording

### PR DESCRIPTION
**Pull request by katsy**
I can't get this flatpak to build on my local system so I'm just going to ram it into the flatbot and see if it works

### CODE REVIEW

**Comment by Lonsfor** [comment]
the runtime already has libvpx and it already done in #10

**Comment by Lonsfor** [comment]
also you are getting libyuv from the latest commit that might not be stable

**Comment by katsy** [comment]
I changed to point at latest commit on chromium's stable branch. I do have a question what "libyup" is though. Is your PR targeting a modified library called "libyup" or it just a mirrored repo of libyuv?

**Comment by Lonsfor** [comment]
its the debian repo since there are no tags for it in the google repo and if its good enough for debian is good enough for this

**Comment by Lonsfor** [comment]
but again the work is already done and tested

**Pull request closed without merging**
